### ISSUE TITLE
Convert bundle to standalone library

### ISSUE THREAD

**Issue by hayellis** [ddeboer/DdeboerDataImportBundle#11]
Hi,

I'we been mucking about with your import bundle for a while now. I'we noticed that you aren't really dependent on symfony or the bundle concept (Except for the three service definitions in services.xml). Wouldn't it be awesome to extract the library into its own ecosystem and have a bundle to bridge symfony and the library?

**Comment by ddeboer** [comment]
Yes, it would indeed! As a matter of fact, I've been thinking about extracting this bundle into a separate library for some time now. I just have to find the time to do it. ;)

**Comment by ddeboer** [comment]
Done, see https://github.com/ddeboer/data-import.
