### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by zerospaceICT** [ddeboer/DdeboerDataImportBundle#14]
Hi,

I would love to use your CSV solution within my Symfony2 (version 2.4) but after setting:

composer require ddeboer/data-import-bundle:dev-master

I get the following error:

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ddeboer/data-import-bundle dev-master -> satisfiable by ddeboer/data-import-bundle[dev-master].
    - ddeboer/data-import-bundle dev-master requires ddeboer/data-import dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.

Could you point me in the right direction in order to use the CSV solutions provided within your bundle?

Thank you in advance.

**Comment by ddeboer** [comment]
Your issue should be fixed now. Can you confirm?

**Comment by zerospaceICT** [comment]
Thank you, the issue is indeed fixed.
