### ISSUE TITLE
Bundle Support

### ISSUE THREAD

**Issue by xtrasmal** [ddeboer/DdeboerDataImportBundle#17]
Hi there,

@author: How do you feel about the support for this bundle. 
Will you be giving long time support? Do you use the bundle yourself? 

Do you have anything to share, before I will be using this bundle in a enterrprise application.

**Comment by ddeboer** [comment]
Please use https://github.com/phpforce/salesforce-bundle instead of this bundle.

**Comment by ddeboer** [comment]
This bundle is only a small wrapper about the [data-import library](https://github.com/ddeboer/data-import), which is used by many people. Please see the library’s pages to get an impression of activity and level of support.
