### ISSUE TITLE
Association support

### ISSUE THREAD

**Issue by Baachi** [ddeboer/DdeboerDataImportBundle#5]
It would be helpful, if the doctrine reader support associations.

**Comment by ddeboer** [comment]
Hey Baachi, good suggestion. Currently one supplies the object (entity) name into the Doctrine reader's constructor. What about changing that argument to a `query` argument, allowing the user to enter any select query, including relations?

**Comment by Baachi** [comment]
Yes this change would help. :)
I think it would be also nice, if the `$query` argument accept a `QueryBuilder` instance, too. :)

**Comment by ddeboer** [comment]
Feel like creating a PR? :)

**Comment by Baachi** [comment]
I will do it :)

**Comment by ddeboer** [comment]
Implemented in @Baachi's PR #7.
